language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
  - setup=basic

matrix:
  include:
  - php: 7.3
    env: setup=lowest

sudo: false

before_install:
- travis_retry composer self-update

install:
- if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
- if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
